version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/v1.14"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/v1.15"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/v1.15-staging"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
