version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/v1.11"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/v1.12"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/v1.13"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/v1.14"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
